version: '3.8'
services:
  jackal-sensors:
    build: sensors/
    image: dcist-jackal-deimos:sensors
    network_mode: host
    privileged: true
    tty: true
    environment: 
      - GPS=false
      - EVENT=false
      - IR=false
      - RGB=true
      - OUSTER=false
      - ZED=true
      - ROS_IP=127.0.0.1
      - ROS_MASTER_URI=http://127.0.0.1:11311/
      - TERM=xterm-256color
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
      - PULSE_SERVER=unix:/run/user/1000/pulse/native 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - ./data:/home/dtc/data
      - ./sensors/launch/camera.launch:/home/dtc/ws/src/flir_camera_driver/spinnaker_camera_driver/launch/camera.launch
    entrypoint: /home/dtc/entrypoint.bash
    logging:
      driver: "local"
      options:
          max-size: "100000" 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

